#!/usr/bin/env python3
"""
Migrate tree_evidences.global_vector column to new dimension.

Usage:
    python scripts/migrate_vector_dimension.py [--dim 768]

This script:
1. Reads the target dimension from environment (POSTGRES_VECTOR_DIM) or command line
2. Connects to PostgreSQL
3. Alters the global_vector column from halfvec(old_dim) to halfvec(new_dim)

WARNING: This clears existing vector data during migration.
         New vectors will be generated by the DINO model during re-ingestion.
"""

import os
import sys
import argparse
import logging

# Add project root to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)-8s | %(name)s | %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger(__name__)


def main():
    parser = argparse.ArgumentParser(description="Migrate tree_evidences.global_vector to new dimension")
    parser.add_argument(
        "--dim",
        type=int,
        default=None,
        help="Target vector dimension (default: POSTGRES_VECTOR_DIM env var or 768)",
    )
    args = parser.parse_args()

    # Get target dimension
    target_dim = args.dim
    if target_dim is None:
        target_dim = int(os.getenv("POSTGRES_VECTOR_DIM", "768"))
    
    logger.info(f"Starting migration to dimension: {target_dim}")

    # Initialize database using app config
    from src.config.appConfig import get_config
    from src.repository.databaseManager import init_db, migrate_vector_dimension
    
    try:
        # Get app config (loads from env/settings)
        config = get_config()
        
        # Initialize database connection
        manager = init_db(app_config=config)
        
        if manager is None or not manager.is_connected:
            logger.error("Database connection failed. Check if psycopg2 is installed and database is running.")
            sys.exit(1)
        
        logger.info(f"Database connection established: {config.postgres_host}:{config.postgres_port}/{config.postgres_db}")
    except ImportError as e:
        logger.error(f"Missing dependency: {e}")
        logger.error("Install required: pip install psycopg2-binary sqlalchemy geoalchemy2 pgvector")
        sys.exit(1)
    except Exception as e:
        logger.error(f"Failed to initialize database: {e}")
        sys.exit(1)

    # Run migration
    success = migrate_vector_dimension(target_dim)
    
    if success:
        logger.info(f"✓ Migration to halfvec({target_dim}) completed successfully")
        sys.exit(0)
    else:
        logger.error(f"✗ Migration failed")
        sys.exit(1)


if __name__ == "__main__":
    main()
